[tool.braindead.config]
base_url = "https://grski.pl/"  # give full url ending with slash here
dist_dir = "public"
title = "The Engineer"
description = "On AI/LLMs, Python, building stuff and my life."
content = ""
name = "grski.pl"
logo = "logo_url"
heading = "The Engineer by Olaf Górski - on Python/AI/LLMs and my life."
github = "https://github.com/grski"
linkedin = "https://www.linkedin.com/in/olafgorski/"
copy_text = "Olaf Górski"
copy_link = "https://grski.pl"
language = "pl"

[tool.braindead.config.i18n]
languages = ["en", "pl"]
